import React, { useEffect, useRef } from "react";
import Typed from "typed.js";
import { Link } from "react-router-dom";
import "./App.css";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import img1 from "./assets/Jack_Turner.png";
import img2 from "./assets/jeremy_chen.jpg";
import img3 from "./assets/grant_balcke.jpg";
import img4 from "./assets/coach_john.jpg";
import img5 from "./assets/jasmine_lai.jpg";
import img6 from "./assets/tj.jpg";




export default function App() {
  const el = useRef(null);

  useEffect(() => {
    const options = {
      strings: [
        " the best golf stats tracking tool",
        " your personal golf performance tracker",
        " the ultimate golf stats app",
        " your gateway to better golf",
      ],
      typeSpeed: 50,
      backSpeed: 70,
      loop: true,
      backDelay: 1000,
      showCursor: true,
      cursorChar: "|",
    };

    const typed = new Typed(el.current, options);

    return () => {
      typed.destroy();
    };
  }, []);

  return (
    <main>
      <div className="center-content">
        <header>
          <h1 id="title">Welcome to GolfStats</h1>
        </header>
        <p className="description">
          GolfStats is{" "}
          <span className="auto-type" ref={el}>
            {" "}
          </span>
        </p>



        <h2 id="offering">What Does GolfStats Offer?</h2>
        
        <div className="offerings">
          <div className="offer">
            <div className="panel">
              <h2>Reliability</h2>
            </div>
            <div className="content">
              <h4 className="content-description">A tool made by a golfer, for golfers. GolfStats ensures that its users and players find improvement through the app, fostering trust and confidence among its users in their pursuit of improvement on the golf course.</h4>
            </div>
          </div>
          <div className="offer">
            <div className="panel">
              <h2>Accuracy</h2>
            </div>
            <div className="content">

              <h4 className="content-description">Meticulously considering over 50 input parameters and 27 derived parameters, GolfStats maintains the rigor in accuracy that modern golf stats tracking apps do, focusing on crucial metrics rather than redudant ones.</h4>
            </div>
          </div>
          <div className="offer">
            <div className="panel">
              <h2>Efficiency</h2>
            </div>
            <div className="content">
              <h4 className="content-description">GolfStats significantly reduces the time required for post round stats entry, with users experiencing an average reduction of 13 minutes for inputting stats for all 18 holes, allowing golfers to spend more time on improving their game rather than administrative tasks.</h4>
            </div>
          </div>
        </div>


        <h2 id="timeline-title">How to use GolfStats?</h2>
        
        <div className="timeline">
          <div className="checkpoint">
            <h2 className="step-title">Play a round of golf</h2>
            <h4 className="step-description">While obvious, go play and round of golf and enjoy the golf course before you have to enter in your statistics! Rememberm GolfStats is only useful if you have stats to actually enter...</h4>
          </div>
          <div className="checkpoint">
            <h2 className="step-title">Enter your stats</h2>
            <h4 className="step-description">After you finish playing your round of golf, begin by entering in your hole by hole, shot by shot, information. These values will be used to calculate certain derived values that are key to generating an accurate and throrough summary of your round.</h4>
          </div>
          <div className="checkpoint">
            <h2 className="step-title">View your summary</h2>
            <h4 className="step-description">After entering in your stats, you can view your summary that is autogenerated by GolfStats. You will be able to view the specifics of your golf round along with graphs and charts depicting the inputted and derived parameters whilst showing it in an easy-to-understand manner.</h4>
          </div>
          <div className="checkpoint">
            <h2 className="step-title">Practice and Improve</h2>
            <h4 className="step-description">After viewing your summary and identifying what you need to improve on by comparing your stats to the tour standard, go out to the range, practice, and repeat!</h4>
          </div>
        </div>


        <h2 id="testimonial-title">Testimonials</h2>

        
        
        <div className="testimonial-grid">
          <div className="testimonial-image">
            <img src={img1} alt="Testimonial 1" />
            <div className="overlay">
              <div className="overlay-text">"Tracking stats post-round used to be a real headache, but this app makes it so much easier. It's intuitive and insightful, and it gives me the edge I need to sharpen my game." ~ Jack Turner, D1 Golfer at University of Florida</div>
            </div>
          </div>
          <div className="testimonial-image">
            <img src={img2} alt="Testimonial 2" />
            <div className="overlay">
              <div className="overlay-text"> "Compared to previous apps I've used, GolfStats is straightforward, smart, and has definitely helped me up my game and hone in on areas of improvement." ~ Jeremy Chen, D1 Golfer at Northwestern University</div>
            </div> 
          </div>
          <div className="testimonial-image">
            <img src={img3} alt="Testimonial 3" />
            <div className="overlay">
              <div className="overlay-text">"As a professional coach for over 20 years, I've seen my fair share of stat-tracking apps. This one stands out for its simplicity and depth. It's a fantastic tool for both amateurs and juniors alike, providing actionable insights while maintaining coherence." ~ Grant Balke, PGA Certified Golf Instructor</div>
            </div>
          </div>
          <div className="testimonial-image">
            <img src={img4} alt="Testimonial 4" />
            <div className="overlay">
              <div className="overlay-text">""As a golf instructor, I'm constantly striving to stay ahead of the curve and provide the best possible experience for my students. This app allows me to do just that - keep it sharp, keep it simple. " ~ John Galyean, PGA Certified Golf Instructor</div>
            </div>
          </div>
          <div className="testimonial-image">
            <img src={img5} alt="Testimonial 5" />
            <div className="overlay">
              <div className="overlay-text">"I used to dread the post-round analysis due to the excessive amounts of time it took, but with GolfStats that has totally changed. I am able to waste less time entering in convoluted stats and focus on whats easy for me to understand." ~ Jasmine Lai, D1 Golfer at Georgetown University</div>
            </div>
          </div>
          <div className="testimonial-image">
            <img src={img6} alt="Testimonial 6" />
            <div className="overlay">
              <div className="overlay-text">"Being a college athlete means balancing academics, training, and competition. This app has been a game-changer for me. It streamlines my post-round analysis, giving me valuable insights into my performance that I can use to stay ahead of the competition." ~ Tina Jiang, D1 Golfer at the University of British Columbia, Vancouver</div>
            </div>
          </div>
        </div>



        <Link to="/beginning">
          <button id="proceed1">Get Started</button>
        </Link>


      </div>


      
    </main>
  );
}



